### ISSUE TITLE
Well concerning the hacks 

### ISSUE THREAD

**Issue by Laughative** [ThatFruedDued/blooket-utility#45]
**I understand you stopped working on this and my question was when do you plan on updating it?** because there is a **winter break** coming up and that's a lot of free time to get back to work. But **I started getting into hacks for blooket after you took a break** and **I have no clue if you were able to bypass the code from keeping glixxy from going past 500 coins and unlocking all the blooks permanently** which would help out to getting space blooks and etc.

**Comment by ThatFruedDued** [comment]
Hello,

I will not be updating this over winter break. I will be using winter break to spend time with my family. It is also important to understand that the way I inject scripts into Blooket requires basically a fresh rewrite of thousands of lines every time Blooket changes one small thing. Also, since I stopped updating this, Blooket has made several updates that vastly increase the difficulty of updating and would require rewrites of essential systems on top of the already strenuous process of updating.

In terms of limitations, going past 500 tokens per day is not possible by reasonable means. Unlocking all blooks permanently without spending tokens and opening boxes is completely impossible due to logic for this being server side.

Thanks for your interest in this project!

**Comment by wolfgoo** [comment]
I not have winter break :(

**Comment by ThatFruedDued** [comment]
Update: the public beta is out! Refer to the pinned issue for more details.
