### ISSUE TITLE
Hey Quick Question

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [ThatFruedDued/blooket-utility#68]
Hey, quick question, are you working on any injectables at the moment? If so can I know what they are I'm really curious?

**Comment by Blooket-dude** [comment]
@ThatFruedDued

**Comment by ThatFruedDued** [comment]
I have a couple ideas, but I'm currently in a phase where making them doesn't really interest me, so it might be a while before anything new happens. Here are some possible things for the future:

1. Simulated server, where you could simulate different stats, tokens, blooks, etc, just to test things out
2. I know the "spoof plus" feature has been wanted for a while, so that could be a potential feature
3. Another possible injectable would be a full replacement for what Gliz's hacks were, I really don't want to integrate School Cheats's version because I honestly just don't trust them

**Comment by Snowflake-Coder-H2o** [comment]
@ThatFruedDued Are you still in a phase where you dont wanna do anything?

**Comment by ThatFruedDued** [comment]
Yeah, I've been really busy with school lately. Hopefully once I finish my AP classes (late April/early May) I should be free enough to work more on this project.

**Comment by Snowflake-Coder-H2o** [comment]
Oh ok! Wait are you in collage?

-Snow
