### ISSUE TITLE
Unable to inject .json file

### ISSUE THREAD

**Issue by UltraWyatt** [ThatFruedDued/blooket-utility#70]
when i go to the configuration page and attempt to inject a file it says invalid injection.

**Comment by ThatFruedDued** [comment]
Not just any `.json` files work, the `.json` file must be made explicitly as an injectable. This is because the `.json` file format stands for JavaScript Object Notation, which is easy to use with this Blooket Utility, but it can also represent various types of data. Please make sure your `.json` file was intended for this Blooket Utility.

**Comment by UltraWyatt** [comment]
used the ones from your repo and still says invalid

**Comment by ThatFruedDued** [comment]
Please send the link you used.

**Comment by UltraWyatt** [comment]
https://github.com/ThatFruedDued/blooket-utility-injectables/blob/main/injectables/glixzzy/injectable.json

sorry i've been offline for a bit

**Comment by ThatFruedDued** [comment]
Two things:
1. Use the github.io link rather than the github.com link. The github.com link is actually an HTML file so your browser can properly display the webpage (you can see all that extra data [here](view-source:https://github.com/ThatFruedDued/blooket-utility-injectables/blob/main/injectables/glixzzy/injectable.json)). [This](https://thatfrueddued.github.io/blooket-utility-injectables/injectables/glixzzy/injectable.json) would be the proper URL to use in the future.
2. The Glixzzy injectable does not function at all anymore due to his legal standing with Blooket. Even if you were to successfully install it, it would not work.
