### ISSUE TITLE
why is my screen white when I open blooket?

### ISSUE THREAD

**Issue by Hankypoo7** [ThatFruedDued/blooket-utility#77]
idk why its white, does that mean I got blacklisted or something from blooket?

**Comment by hxc4life07** [comment]
It can be some reasons:
1.- you have been banned and you need to relogin to see the message
2.- There is an issue (it also used to happen on the old utility
3.- check your connection or relogin for the pace to work (if it is posible)
4.- delete the cookies or use the test option on blooket-utility.okr765.com/reset

**Comment by ThatFruedDued** [comment]
Blooket was down last night. This issue has now been fixed by Blooket.

**Comment by Phoenix9999999999** [comment]
Guys can you pls tell me why my blooket isn't working?
Because I was casually hacking then I shut down my laptop and when I went back on the screens were blank and on the play button there was a create button and there wasn't a section of the blooks.
But also it didn't say my blooket was suspended? and it let me login completely fine.
